import { timestamp, uuid } from 'drizzle-orm/pg-core'

/**
 * Columns every table carries (spec §8): a uuid primary key generated by
 * Postgres, and created/updated timestamps stored in UTC.
 */
export const id = () => uuid().primaryKey().defaultRandom()

export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
}
